name: Tests

on:
  push:
  pull_request:

permissions:
  contents: read
  packages: write

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set Up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r requirements-dev.txt

      - name: Run Tests
        run: pytest -v

      - name: Build Docker Image
        run: docker build -t task-api .

      - name: Run Docker Container
        run: |
          docker run -d --name task-api -p 8000:8000 task-api
      
      - name: Check Application
        run: |
          sleep 3
          curl --fail http://localhost:8000/health

      - name: Log into GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}

      - name: Tag Docker image
        run: |
          IMAGE_NAME=$(echo "${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]')

          docker tag task-api \
            ghcr.io/$IMAGE_NAME/task-api:${{ github.sha }}

          docker tag task-api \
            ghcr.io/$IMAGE_NAME/task-api:latest

      - name: Push Docker image
        run: |
          IMAGE_NAME=$(echo "${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]')

          docker push ghcr.io/$IMAGE_NAME/task-api:${{ github.sha }}
          docker push ghcr.io/$IMAGE_NAME/task-api:latest
